version: '2'

services:
    frontend:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    backend0:
        image: php:fpm-alpine
        volumes:
            - ./public_html0:/var/www/html
    backend1:
        image: php:fpm-alpine
        volumes:
            - ./public_html1:/var/www/html
